name: libello
description: A note taking application for pros

publish_to: 'none'
repository: 'https://github.com/quabynah-bilson/libello'
homepage: 'https://github.com/quabynah-bilson/libello'
issue_tracker: 'https://github.com/quabynah-bilson/libello/issues'

version: 0.0.0-alpha+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route:
  json_annotation:
  bloc:
  flutter_bloc:
  dartz:
  lottie:
  flutter_staggered_grid_view:
  flutter_staggered_animations:
  shared_preferences:
  google_fonts:
  logger:
  flutter_tabler_icons:
  get_it:
  uuid:
  string_stats:
  animated_bottom_navigation_bar:
  flutter_multi_formatter:
  copy_with_extension:
  date_time_format:
  timeago_flutter:
  fl_chart: ^0.55.2
  flutter_palette:
  google_sign_in:
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.4
  firebase_auth: ^4.1.1
  share_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  json_serializable:
  auto_route_generator:
  flutter_native_splash:
  flutter_launcher_icons:
  copy_with_extension_gen:

flutter:
  uses-material-design: true
  assets:
    - assets/

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/logo.png
  image_dark: assets/logo.png
  icon_background_color: "#ffffff"
  color: "#ffffff"
  color_dark: "#ffffff"
  icon_background_color_dark: "#ffffff"
  web: false
  android_12:
    image: assets/logo.png
    color: "#ffffff"
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#ffffff"
    color_dark: "#ffffff"
    image_dark: assets/logo.png

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
  windows:
    generate: false