// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQj3RlnFCa7Z7xWhYtrOj9644w0R2zex8',
    appId: '1:578565313797:web:f21e5e7affbb6af701d36c',
    messagingSenderId: '578565313797',
    projectId: 'libello-notes',
    authDomain: 'libello-notes.firebaseapp.com',
    storageBucket: 'libello-notes.appspot.com',
    measurementId: 'G-5BH5PM260R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZCFTfe48PmMSF3sP0jqLEnqDSegmkI1Q',
    appId: '1:578565313797:android:cf6411ea22aad3ea01d36c',
    messagingSenderId: '578565313797',
    projectId: 'libello-notes',
    storageBucket: 'libello-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkZdVsHTAazAirUIbsyQQ-EacBa3DDuxI',
    appId: '1:578565313797:ios:d95bad0a08fcf61701d36c',
    messagingSenderId: '578565313797',
    projectId: 'libello-notes',
    storageBucket: 'libello-notes.appspot.com',
    androidClientId: '578565313797-6sh01pk89q6lltjnaioicgk9d9i9j8m6.apps.googleusercontent.com',
    iosClientId: '578565313797-j6ubqtjvbqtlpoc8buljllr1899gluls.apps.googleusercontent.com',
    iosBundleId: 'io.qcodelabs.libello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkZdVsHTAazAirUIbsyQQ-EacBa3DDuxI',
    appId: '1:578565313797:ios:d95bad0a08fcf61701d36c',
    messagingSenderId: '578565313797',
    projectId: 'libello-notes',
    storageBucket: 'libello-notes.appspot.com',
    androidClientId: '578565313797-6sh01pk89q6lltjnaioicgk9d9i9j8m6.apps.googleusercontent.com',
    iosClientId: '578565313797-j6ubqtjvbqtlpoc8buljllr1899gluls.apps.googleusercontent.com',
    iosBundleId: 'io.qcodelabs.libello',
  );
}
